#ifndef _COMMON_DEFS_
#define _COMMON_DEFS_

enum EOS_TYPE {SRK, VDW, PR, GHC}; 

enum FLASH_TYPE {SIMPLE };

enum SIM_TYPE {LIQDENSITY, VAPDENSITY, TPFLASH, PT_DIAGRAM, DEW_POINT, BUBBLE_POINT, PUREPSAT};

#endif
